// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Olympia.Models
{
    /// <summary>
    /// Article
    /// </summary>
    public partial class Art
    {
        public int ArtId { get; set; }
        /// <summary>
        /// Ce1
        /// </summary>
        public string Ce1 { get; set; }
        /// <summary>
        /// Ce2
        /// </summary>
        public string Ce2 { get; set; }
        /// <summary>
        /// Ce3
        /// </summary>
        public string Ce3 { get; set; }
        /// <summary>
        /// Ce4
        /// </summary>
        public string Ce4 { get; set; }
        /// <summary>
        /// Ce5
        /// </summary>
        public string Ce5 { get; set; }
        /// <summary>
        /// Ce6
        /// </summary>
        public string Ce6 { get; set; }
        /// <summary>
        /// Ce7
        /// </summary>
        public string Ce7 { get; set; }
        /// <summary>
        /// Ce8
        /// </summary>
        public string Ce8 { get; set; }
        /// <summary>
        /// Ce9
        /// </summary>
        public string Ce9 { get; set; }
        /// <summary>
        /// CeA
        /// </summary>
        public string Cea { get; set; }
        /// <summary>
        /// Dossier
        /// </summary>
        public decimal Dos { get; set; }
        /// <summary>
        /// Référence
        /// </summary>
        public string Ref { get; set; }
        /// <summary>
        /// Auteur de la création
        /// </summary>
        public string Usercr { get; set; }
        /// <summary>
        /// Auteur de la modification
        /// </summary>
        public string Usermo { get; set; }
        /// <summary>
        /// Code confidentiel
        /// </summary>
        public string Conf { get; set; }
        /// <summary>
        /// Désignation
        /// </summary>
        public string Des { get; set; }
        /// <summary>
        /// Désignation abrégée
        /// </summary>
        public string Desabr { get; set; }
        /// <summary>
        /// Code EAN
        /// </summary>
        public string Ean { get; set; }
        /// <summary>
        /// Code tiers
        /// </summary>
        public string Tiers { get; set; }
        /// <summary>
        /// Référence de tarification
        /// </summary>
        public string Taref { get; set; }
        /// <summary>
        /// Référence de remplacement
        /// </summary>
        public string Refrpl { get; set; }
        /// <summary>
        /// Famille tarif exceptionnelle
        /// </summary>
        public string Tafamrx { get; set; }
        /// <summary>
        /// Famille de tarification
        /// </summary>
        public string Tafamr { get; set; }
        /// <summary>
        /// Famille remise exceptionnelle
        /// </summary>
        public string Refamrx { get; set; }
        /// <summary>
        /// Famille de remise
        /// </summary>
        public string Refamr { get; set; }
        /// <summary>
        /// Famille de commission article
        /// </summary>
        public string Cofamr { get; set; }
        /// <summary>
        /// Famille statistique article
        /// </summary>
        public string Fam0001 { get; set; }
        /// <summary>
        /// Famille statistique article
        /// </summary>
        public string Fam0002 { get; set; }
        /// <summary>
        /// Famille statistique article
        /// </summary>
        public string Fam0003 { get; set; }
        /// <summary>
        /// Nature du produit
        /// </summary>
        public string Prodnat { get; set; }
        /// <summary>
        /// Unité de référence
        /// </summary>
        public string Refun { get; set; }
        /// <summary>
        /// Unité d achat
        /// </summary>
        public string Achun { get; set; }
        /// <summary>
        /// Unité de stockage
        /// </summary>
        public string Stun { get; set; }
        /// <summary>
        /// Unité de vente
        /// </summary>
        public string Venun { get; set; }
        /// <summary>
        /// Unité du poids
        /// </summary>
        public string Poiun { get; set; }
        /// <summary>
        /// Unité du volume
        /// </summary>
        public string Volun { get; set; }
        /// <summary>
        /// Unité des dimensions
        /// </summary>
        public string Dimun { get; set; }
        /// <summary>
        /// Compte de vente
        /// </summary>
        public string Cptv { get; set; }
        /// <summary>
        /// Compte d achat
        /// </summary>
        public string Cpta { get; set; }
        /// <summary>
        /// Compte de stock
        /// </summary>
        public string Cpts { get; set; }
        /// <summary>
        /// Code TPF article
        /// </summary>
        public decimal Tpfr0001 { get; set; }
        /// <summary>
        /// Code TPF article
        /// </summary>
        public decimal Tpfr0002 { get; set; }
        /// <summary>
        /// Code TPF article
        /// </summary>
        public decimal Tpfr0003 { get; set; }
        /// <summary>
        /// Tva nomenclature douane
        /// </summary>
        public string Tvanom { get; set; }
        /// <summary>
        /// Tva unité douanière
        /// </summary>
        public string Tvaun { get; set; }
        /// <summary>
        /// TVA code régime échange
        /// </summary>
        public decimal Tvargcod { get; set; }
        /// <summary>
        /// Code édition
        /// </summary>
        public string Edcod { get; set; }
        /// <summary>
        /// Code grille sous-référence
        /// </summary>
        public string Gricod { get; set; }
        /// <summary>
        /// Zone alpha libre
        /// </summary>
        public string Zona { get; set; }
        /// <summary>
        /// Image multimédia
        /// </summary>
        public string Media { get; set; }
        /// <summary>
        /// Nom de la page html
        /// </summary>
        public string Html { get; set; }
        /// <summary>
        /// Masque analytique
        /// </summary>
        public string Axemsk { get; set; }
        /// <summary>
        /// No axe  analytique
        /// </summary>
        public decimal Axeno { get; set; }
        /// <summary>
        /// Code abc
        /// </summary>
        public string Abccod { get; set; }
        /// <summary>
        /// Questionnaire implicite dynamique
        /// </summary>
        public string Question { get; set; }
        /// <summary>
        /// Code règle de gestion du CBN
        /// </summary>
        public string Cbngescod { get; set; }
        /// <summary>
        /// Unité de l éco-contribution
        /// </summary>
        public string Deeeun { get; set; }
        /// <summary>
        /// Compte de l éco-contribution en vente
        /// </summary>
        public string Deeecptv { get; set; }
        /// <summary>
        /// Compte de l éco-contribution en achat
        /// </summary>
        public string Deeecpta { get; set; }
        /// <summary>
        /// Code compétence
        /// </summary>
        public string Competcod { get; set; }
        /// <summary>
        /// Compte d achat inter établissement
        /// </summary>
        public string Cptaces { get; set; }
        /// <summary>
        /// Compte de vente inter établissement
        /// </summary>
        public string Cptvces { get; set; }
        /// <summary>
        /// Famille de tarification promotion article exceptionnelle
        /// </summary>
        public string Achtafamrx { get; set; }
        /// <summary>
        /// Famille de tarification
        /// </summary>
        public string Achtafamr { get; set; }
        /// <summary>
        /// Classe de remise article achat exceptionnelle
        /// </summary>
        public string Achrefamrx { get; set; }
        /// <summary>
        /// Classe de remise article achat
        /// </summary>
        public string Achrefamr { get; set; }
        /// <summary>
        /// Unité de surface
        /// </summary>
        public string Surfun { get; set; }
        /// <summary>
        /// Coefficient diviseur fidélité
        /// </summary>
        public decimal Coefpts { get; set; }
        /// <summary>
        /// Formulaire du configurateur
        /// </summary>
        public string Configurateurformulaire { get; set; }
        /// <summary>
        /// Chemin du configurateur
        /// </summary>
        public string Configurateurchemincod { get; set; }
        /// <summary>
        /// Flag ordonnancement SMC
        /// </summary>
        public decimal Smcfl { get; set; }
        /// <summary>
        /// Flag visualisation SMC
        /// </summary>
        public decimal Smcvisufl { get; set; }
        /// <summary>
        /// Utilisateur date et heure de création
        /// </summary>
        public DateTime? Usercrdh { get; set; }
        /// <summary>
        /// Utilisateur date et heure de modification
        /// </summary>
        public DateTime? Usermodh { get; set; }
        /// <summary>
        /// Date de fin de validité
        /// </summary>
        public DateTime? Hsdt { get; set; }
        /// <summary>
        /// Date et heure de dernière opération
        /// </summary>
        public DateTime? Dopdh { get; set; }
        /// <summary>
        /// =2 si note&lt;&gt; 0
        /// </summary>
        public decimal Cenote { get; set; }
        /// <summary>
        /// Numéro de note
        /// </summary>
        public decimal Note { get; set; }
        /// <summary>
        /// Masse nette
        /// </summary>
        public decimal Poin { get; set; }
        /// <summary>
        /// Poids brut
        /// </summary>
        public decimal Poib { get; set; }
        /// <summary>
        /// Saisie en mode grille
        /// </summary>
        public decimal Grisais { get; set; }
        /// <summary>
        /// Quantité en réservation client
        /// </summary>
        public decimal Restotqte { get; set; }
        /// <summary>
        /// Quantité en commande client
        /// </summary>
        public decimal Cdeclqte { get; set; }
        /// <summary>
        /// Quantité en commande fournisseur
        /// </summary>
        public decimal Cdefoqte { get; set; }
        /// <summary>
        /// Quantité en stock cumulée
        /// </summary>
        public decimal Sttotqte { get; set; }
        /// <summary>
        /// Date d inventaire
        /// </summary>
        public DateTime? Invdt { get; set; }
        /// <summary>
        /// Durée de garantie
        /// </summary>
        public decimal Garjrnb { get; set; }
        /// <summary>
        /// Code stock / hors stock
        /// </summary>
        public decimal Stcod { get; set; }
        /// <summary>
        /// Code global / individuel
        /// </summary>
        public decimal Gicod { get; set; }
        /// <summary>
        /// Volume
        /// </summary>
        public decimal Vol { get; set; }
        /// <summary>
        /// Dimensions
        /// </summary>
        public decimal Dim0001 { get; set; }
        /// <summary>
        /// Dimensions
        /// </summary>
        public decimal Dim0002 { get; set; }
        /// <summary>
        /// Dimensions
        /// </summary>
        public decimal Dim0003 { get; set; }
        /// <summary>
        /// Gérer sous-référence non/oui
        /// </summary>
        public decimal Srefcod { get; set; }
        /// <summary>
        /// Option saisie vente
        /// </summary>
        public decimal Opsais0001 { get; set; }
        /// <summary>
        /// Option saisie vente
        /// </summary>
        public decimal Opsais0002 { get; set; }
        /// <summary>
        /// Option saisie vente
        /// </summary>
        public decimal Opsais0003 { get; set; }
        /// <summary>
        /// Zone libre numérique
        /// </summary>
        public decimal Zonn { get; set; }
        /// <summary>
        /// Taux de marge
        /// </summary>
        public decimal Mgtx { get; set; }
        /// <summary>
        /// Péremption en nombre de jours
        /// </summary>
        public decimal Perjrnb { get; set; }
        /// <summary>
        /// Méthode de valorisation du stock
        /// </summary>
        public decimal Stvalcod { get; set; }
        /// <summary>
        /// Mode de sortie du stock
        /// </summary>
        public decimal Stsorcod { get; set; }
        /// <summary>
        /// Prise de commande par internet ?
        /// </summary>
        public decimal Webcdecod { get; set; }
        /// <summary>
        /// Code prix de vente
        /// </summary>
        public decimal Pvcod { get; set; }
        /// <summary>
        /// Type de ligne liée
        /// </summary>
        public decimal Lgtyp { get; set; }
        /// <summary>
        /// Réservation du stock ?
        /// </summary>
        public decimal Stres { get; set; }
        /// <summary>
        /// Quantité en OF
        /// </summary>
        public decimal Cdeinqte { get; set; }
        /// <summary>
        /// CE si fichier joint =2 si joint &lt;&gt; 0
        /// </summary>
        public decimal Cejoint { get; set; }
        /// <summary>
        /// Numéro fichier joint
        /// </summary>
        public decimal Joint { get; set; }
        /// <summary>
        /// Prix unitaire éco-contribution
        /// </summary>
        public decimal Deeepu { get; set; }
        /// <summary>
        /// Autoriser le rejalonnement des OFs
        /// </summary>
        public decimal Rejalof { get; set; }
        /// <summary>
        /// Autoriser le rejalonnement des commandes
        /// </summary>
        public decimal Rejalcde { get; set; }
        /// <summary>
        /// Horizon de rejalonnement des OFs
        /// </summary>
        public decimal Rejalofjrnb { get; set; }
        /// <summary>
        /// Horizon de rejalonnement des commandes
        /// </summary>
        public decimal Rejalcdejrnb { get; set; }
        /// <summary>
        /// Taux de tolérance
        /// </summary>
        public decimal Tolerancetx { get; set; }
        /// <summary>
        /// Autoriser saisie de commission
        /// </summary>
        public decimal Comsais { get; set; }
        /// <summary>
        /// Surface
        /// </summary>
        public decimal Surf { get; set; }
        /// <summary>
        /// Coefficient de foisonnement sur le volume
        /// </summary>
        public decimal Coefoivol { get; set; }
        /// <summary>
        /// Unité de manutention
        /// </summary>
        public string Manun { get; set; }
        /// <summary>
        /// Type de catégorie ABC
        /// </summary>
        public string Stlgtabccod { get; set; }
        /// <summary>
        /// Hors gabarit oui/non
        /// </summary>
        public decimal Stlgthgcod { get; set; }
        /// <summary>
        /// Nombre de colis nécessaire hors gabarit
        /// </summary>
        public decimal Stlgthgcolinb { get; set; }
        /// <summary>
        /// Rang calcul ABC
        /// </summary>
        public decimal Rangabc { get; set; }
        /// <summary>
        /// Indicateur PDP Master Product
        /// </summary>
        public decimal Pdp { get; set; }
        /// <summary>
        /// Période PDP
        /// </summary>
        public decimal Pdppercod { get; set; }
        /// <summary>
        /// Délai d obtention PDP
        /// </summary>
        public decimal Pdpdelobt { get; set; }
        /// <summary>
        /// Nombre de périodes PDP ferme
        /// </summary>
        public decimal Pdpfermepernb { get; set; }
        /// <summary>
        /// Nombre de périodes PDP négociable
        /// </summary>
        public decimal Pdpnegopernb { get; set; }
        /// <summary>
        /// Taille de lot PDP
        /// </summary>
        public decimal Pdplotqte { get; set; }
        /// <summary>
        /// Nombre de périodes PDP regroupement
        /// </summary>
        public decimal Pdpregpernb { get; set; }
        /// <summary>
        /// Taux d écart maximum en % pour message PDP
        /// </summary>
        public decimal Pdpecartmax { get; set; }
        /// <summary>
        /// Régime TVA article
        /// </summary>
        public string Tvaart { get; set; }
        /// <summary>
        /// Régime TVA article achat
        /// </summary>
        public string Tvaarta { get; set; }
        /// <summary>
        /// Quantité seuil méthode de réservation en volume important
        /// </summary>
        public decimal U_ACTIF { get; set; }
        public decimal U_PTS { get; set; }
        public decimal Wmqteimp { get; set; }
        public string Dtind { get; set; }
        public decimal Dvno { get; set; }
        public decimal Revuart { get; set; }
        public string Sref1 { get; set; }
        public string Sref2 { get; set; }
        public string Tierscli { get; set; }
        public decimal Wmreapfroidfl { get; set; }
        public decimal Icpfl { get; set; }
        public string Contratcod { get; set; }
        public string Contratfam { get; set; }
        public string Travun { get; set; }
        public decimal Eanautofl { get; set; }
    }
}