// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using lang_server.Models;
using System;
using System.Collections.Generic;

namespace Olympia.Models
{
    public partial class Authentication
    {
        public int? Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string? Role { get; set; }
        // 🔽 nouveaux champs
        public int? DOS { get; set; }   // numeric(3,0)
        public string? ETB { get; set; } // char(3)

        public string? DEPOT { get; set; } // char(3)


    }
}
