// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using lang_server.Models;
using Microsoft.EntityFrameworkCore;

namespace Olympia.Models
{
    public partial class ERP210OLYMPIA_FContext : DbContext
    {
        public ERP210OLYMPIA_FContext()
        {
        }

        public ERP210OLYMPIA_FContext(DbContextOptions<ERP210OLYMPIA_FContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Art> Art { get; set; }
        public virtual DbSet<Tar> Tar { get; set; }
        public virtual DbSet<CLI> CLI { get; set; }
        public virtual DbSet<Adresse> Adresses { get; set; }

        public virtual DbSet<ChangePasswordRequest> ChangePasswordRequest { get; set; }

        public virtual DbSet<Authentication> Authentication { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<T006> T006 { get; set; }
        public virtual DbSet<T012> T012 { get; set; }
        public virtual DbSet<T019> T019 { get; set; }
        public virtual DbSet<CommandeArticle> CommandeArticle { get; set; }
        public virtual DbSet<VRP> VRP { get; set; }
        public virtual DbSet<Tre> Tre { get; set; }
        public virtual DbSet<T035> T035 { get; set; }
        public virtual DbSet<TarRemise> AbTarRemise { get; set; }
        public virtual DbSet<T2> T2 { get; set; }

        public virtual DbSet<Guest> Guest { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Latin1_General_BIN");
            modelBuilder.Entity<CommandeArticle>(entity =>
            {
                entity.ToTable("CommandeArticle");
                entity.HasKey(ca => new { ca.CommandeId, ca.ArticleId });
                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.CommandeArticle_Id);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Dos);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.CE4);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.ArticleId);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Quantite);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Fquantite);

                modelBuilder.Entity<CommandeArticle>()
                   .Property(ca => ca.Stock);
                
                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Eche);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Tarif);
                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.ContactId);

                modelBuilder.Entity<CommandeArticle>()
                   .Property(ca => ca.U_PTS);

                modelBuilder.Entity<CommandeArticle>()
                   .Property(ca => ca.Fidelity);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Ref);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Sref1);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.Sref2);

                modelBuilder.Entity<CommandeArticle>()
                    .Property(ca => ca.CommandeId);

                modelBuilder.Entity<CommandeArticle>()
                    .ToTable("CommandeArticle");

            });

            modelBuilder.Entity<Adresse>(entity =>
            {
                entity.ToTable("Adresses");

                entity.HasKey(e => e.Adresse_Id);

                entity.Property(e => e.Adresse_Id)
                      .HasColumnName("Adresse_Id");

                entity.Property(e => e.Commande_Id)
                      .HasColumnName("Commande_Id")
                      .IsRequired();

                entity.Property(e => e.Adresse_Facturation)
                      .HasColumnName("Adresse_Facturation")
                      .HasMaxLength(255)
                      .IsUnicode(true)
                      .IsRequired(false);

                entity.Property(e => e.Adresse_Livraison)
                      .HasColumnName("Adresse_Livraison")
                      .HasMaxLength(255)
                      .IsUnicode(true)
                      .IsRequired(false);

                
            });


            modelBuilder.Entity<T2>(entity =>
            {
                entity.ToTable("T2");

                entity.HasKey(e => e.T2_ID);

                entity.Property(e => e.T2_ID).HasColumnName("T2_ID");


                entity.Property(e => e.DOS).HasColumnType("numeric(3, 0)").IsRequired();
                entity.Property(e => e.TIERS).HasColumnType("char(8)").IsRequired();
                entity.Property(e => e.USERCR).HasColumnType("char(20)").IsRequired();
                entity.Property(e => e.USERMO).HasColumnType("char(20)").IsRequired();
                entity.Property(e => e.CONTACT).HasColumnType("char(8)").IsRequired();
                entity.Property(e => e.NOM).HasColumnType("char(38)").IsRequired();
                entity.Property(e => e.TEL).HasColumnType("char(20)").IsRequired();
                entity.Property(e => e.TELGSM).HasColumnType("char(20)").IsRequired();
                entity.Property(e => e.FAX).HasColumnType("char(20)").IsRequired();
                entity.Property(e => e.EMAIL).HasColumnType("char(80)").IsRequired();
                // 🔽 nouveaux champs
                entity.Property(e => e.U_DEPOT)
                    .HasColumnType("char(3)")
                    .IsRequired();

                entity.Property(e => e.U_ETB)
                    .HasColumnType("char(3)")
                    .IsRequired();


            });
            modelBuilder.Entity<VRP>(entity =>
            {
                entity.ToTable("VRP");

                entity.HasKey(e => e.VRP_ID);


            });
            modelBuilder.Entity<TarRemise>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("TarRemise");

                entity.Property(e => e.Dos);

                entity.Property(e => e.Lib)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Ref)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Rem0001);

                entity.Property(e => e.Rem0002);

                entity.Property(e => e.Remcod)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Sref1)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Sref2)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .IsFixedLength();
            });
            modelBuilder.Entity<T035>(entity =>
            {
                entity.HasComment("Code remise");

                entity.HasIndex(e => new { e.Dos, e.Cebin, e.Ticod, e.Remcod, e.T035Id }, "INDEX_A_T035");

                entity.Property(e => e.T035Id).HasColumnName("T035_ID");

                entity.Property(e => e.Cebin)
                    .HasColumnName("CEBIN")
                    .HasComment("CE binaire");

                entity.Property(e => e.Cenote)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("CENOTE")
                    .HasComment("=2 si note<> 0");

                entity.Property(e => e.Dos)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("DOS")
                    .IsFixedLength()
                    .HasComment("Dossier");

                entity.Property(e => e.Lib)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("LIB")
                    .IsFixedLength()
                    .HasComment("Libellé");

                entity.Property(e => e.Note)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("NOTE")
                    .HasComment("Numéro de note");

                entity.Property(e => e.Remcod)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("REMCOD")
                    .IsFixedLength()
                    .HasComment("Code remise");

                entity.Property(e => e.Tabno)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("TABNO")
                    .HasComment("Numéro table de gtftab");

                entity.Property(e => e.Ticod)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("TICOD")
                    .IsFixedLength()
                    .HasComment("Type de tiers");

                entity.Property(e => e.Usercr)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERCR")
                    .IsFixedLength()
                    .HasComment("Auteur de la création");

                entity.Property(e => e.Usercrdh)
                    .HasColumnName("USERCRDH")
                    .HasComment("Utilisateur date et heure de création");

                entity.Property(e => e.Usermo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERMO")
                    .IsFixedLength()
                    .HasComment("Auteur de la modification");

                entity.Property(e => e.Usermodh)
                    .HasColumnName("USERMODH")
                    .HasComment("Utilisateur date et heure de modification");
            });
            modelBuilder.Entity<Tre>(entity =>
            {
                entity.ToTable("TRE");

                entity.HasComment("Remise de vente");

                entity.HasIndex(e => new { e.Dos, e.Ref, e.Sref1, e.Sref2, e.Tiers, e.Marche, e.Remcod, e.Remdt, e.Qte, e.TreId }, "INDEX_S");

                entity.HasIndex(e => new { e.Dos, e.Remcod, e.Tiers, e.Marche, e.Ref, e.Sref1, e.Sref2, e.Remdt, e.Qte, e.TreId }, "INDEX_T");

                entity.Property(e => e.TreId).HasColumnName("TRE_ID");

                entity.Property(e => e.Ce1)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE1")
                    .IsFixedLength()
                    .HasComment("Ce1");

                entity.Property(e => e.Ce2)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE2")
                    .IsFixedLength()
                    .HasComment("Ce2");

                entity.Property(e => e.Ce3)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE3")
                    .IsFixedLength()
                    .HasComment("Ce3");

                entity.Property(e => e.Ce4)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE4")
                    .IsFixedLength()
                    .HasComment("Ce4");

                entity.Property(e => e.Ce5)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE5")
                    .IsFixedLength()
                    .HasComment("Ce5");

                entity.Property(e => e.Ce6)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE6")
                    .IsFixedLength()
                    .HasComment("Ce6");

                entity.Property(e => e.Ce7)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE7")
                    .IsFixedLength()
                    .HasComment("Ce7");

                entity.Property(e => e.Ce8)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE8")
                    .IsFixedLength()
                    .HasComment("Ce8");

                entity.Property(e => e.Ce9)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE9")
                    .IsFixedLength()
                    .HasComment("Ce9");

                entity.Property(e => e.Cea)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CEA")
                    .IsFixedLength()
                    .HasComment("CeA");

                entity.Property(e => e.Cenote)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("CENOTE")
                    .HasComment("=2 si note<> 0");

                entity.Property(e => e.Conf)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("CONF")
                    .IsFixedLength()
                    .HasComment("Code confidentiel");

                entity.Property(e => e.Dev)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("DEV")
                    .IsFixedLength()
                    .HasComment("Devise");

                entity.Property(e => e.Dos)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("DOS")
                    .HasComment("Dossier");

                entity.Property(e => e.Hsdt)
                    .HasColumnType("date")
                    .HasColumnName("HSDT")
                    .HasComment("Date de fin de validité");

                entity.Property(e => e.Icpfl)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("ICPFL")
                    .HasComment("Element synchronisé en inter-compagnies");

                entity.Property(e => e.Marche)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("MARCHE")
                    .IsFixedLength()
                    .HasComment("Code marché");

                entity.Property(e => e.Marqte)
                    .HasColumnType("numeric(12, 3)")
                    .HasColumnName("MARQTE")
                    .HasComment("Quantité engagement pour le marché");

                entity.Property(e => e.Note)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("NOTE")
                    .HasComment("Numéro de note");

                entity.Property(e => e.Qte)
                    .HasColumnType("numeric(12, 3)")
                    .HasColumnName("QTE")
                    .HasComment("Quantité");

                entity.Property(e => e.Ref)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("REF")
                    .IsFixedLength()
                    .HasComment("Référence");

                entity.Property(e => e.Rem0001)
                    .HasColumnType("numeric(6, 2)")
                    .HasColumnName("REM_0001")
                    .HasComment("Remise");

                entity.Property(e => e.Rem0002)
                    .HasColumnType("numeric(6, 2)")
                    .HasColumnName("REM_0002")
                    .HasComment("Remise");

                entity.Property(e => e.Rem0003)
                    .HasColumnType("numeric(6, 2)")
                    .HasColumnName("REM_0003")
                    .HasComment("Remise");

                entity.Property(e => e.Remcod)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("REMCOD")
                    .IsFixedLength()
                    .HasComment("Code remise");

                entity.Property(e => e.Remdt)
                    .HasColumnType("date")
                    .HasColumnName("REMDT")
                    .HasComment("Date d application de la remise");

                entity.Property(e => e.Remmt)
                    .HasColumnType("numeric(9, 3)")
                    .HasColumnName("REMMT")
                    .HasComment("Remise en montant");

                entity.Property(e => e.Remtyp0001)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("REMTYP_0001")
                    .HasComment("Type de remise");

                entity.Property(e => e.Remtyp0002)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("REMTYP_0002")
                    .HasComment("Type de remise");

                entity.Property(e => e.Remtyp0003)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("REMTYP_0003")
                    .HasComment("Type de remise");

                entity.Property(e => e.Sref1)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SREF1")
                    .IsFixedLength()
                    .HasComment("Sous-référence 1");

                entity.Property(e => e.Sref2)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SREF2")
                    .IsFixedLength()
                    .HasComment("Sous-référence 2");

                entity.Property(e => e.Tiers)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TIERS")
                    .IsFixedLength()
                    .HasComment("Code tiers");

                entity.Property(e => e.Usercr)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERCR")
                    .IsFixedLength()
                    .HasComment("Auteur de la création");

                entity.Property(e => e.Usercrdh)
                    .HasColumnName("USERCRDH")
                    .HasComment("Utilisateur date et heure de création");

                entity.Property(e => e.Usermo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERMO")
                    .IsFixedLength()
                    .HasComment("Auteur de la modification");

                entity.Property(e => e.Usermodh)
                    .HasColumnName("USERMODH")
                    .HasComment("Utilisateur date et heure de modification");
            });
            modelBuilder.Entity<Commande>(entity =>
            {
                modelBuilder.Entity<Commande>()
                    .HasKey(c => c.Commande_Id);
                entity.ToTable("Commande");

                modelBuilder.Entity<Commande>()
                    .Property(c => c.Commande_Id);

                modelBuilder.Entity<Commande>()
                    .Property(c => c.ClientId);
                
                modelBuilder.Entity<Commande>()
                    .Property(c => c.ContactId);

                modelBuilder.Entity<Commande>()
                    .Property(c => c.OrderDate);

                modelBuilder.Entity<Commande>()
                    .Property(c => c.Total);

                modelBuilder.Entity<Commande>()
                    .Property(c => c.Status);

                modelBuilder.Entity<Commande>()
                    .Property(c => c.Tiers);

                modelBuilder.Entity<Commande>()
                    .Property(c => c.CE4);

                modelBuilder.Entity<Commande>()
                    .Property(c => c.Pino);
                modelBuilder.Entity<Commande>()
                  .Property(c => c.Reglement);
                modelBuilder.Entity<Commande>()
                  .Property(c => c.Dos);
                modelBuilder.Entity<Commande>()
                  .Property(c => c.GuestId);
                modelBuilder.Entity<Commande>()
                  .Property(c => c.Type);
            });
            modelBuilder.Entity<Authentication>(entity =>
            {
                entity.ToTable("Authentication");

                entity.HasKey(e => e.Id);


                entity.Property(e => e.Password)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Username)
                    .HasMaxLength(50)
                    .IsUnicode(false);
                // 🔽 ajout mapping
                entity.Property(e => e.DOS)
                    .HasColumnType("numeric(3,0)");

                entity.Property(e => e.ETB)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .IsFixedLength(true); // important pour char(3)
            });

            modelBuilder.Entity<CLI>(entity =>
            {
                entity.ToTable("CLI"); // Nom de la table dans la base de données

                entity.HasKey(e => e.CLI_ID); // Clé primaire

                // Configuration des propriétés
                entity.Property(e => e.CLI_ID).HasColumnName("CLI_ID");
                entity.Property(e => e.DOS).HasColumnName("DOS");
                entity.Property(e => e.U_RDV).HasColumnName("U_RDV");
                entity.Property(e => e.RUE).HasColumnName("RUE");
                entity.Property(e => e.LOC).HasColumnName("LOC");
                entity.Property(e => e.VIL).HasColumnName("VIL");
                entity.Property(e => e.PAY).HasColumnName("PAY");
                entity.Property(e => e.CPOSTAL).HasColumnName("CPOSTAL");
                entity.Property(e => e.REGIONCOD).HasColumnName("REGIONCOD");
                entity.Property(e => e.TEL).HasColumnName("TEL");
                entity.Property(e => e.FAX).HasColumnName("FAX");
                entity.Property(e => e.WEB).HasColumnName("WEB");
                entity.Property(e => e.EMAIL).HasColumnName("EMAIL");
                entity.Property(e => e.NOM).HasColumnName("NOM");
                entity.Property(e => e.REMCOD).HasColumnName("REMCOD");
                entity.Property(e => e.TIERS).HasColumnName("TIERS");

            });
            modelBuilder.Entity<Art>(entity =>
            {
                entity.ToTable("ART");

                entity.HasComment("Article");

                entity.HasIndex(e => new { e.Dos, e.Ref, e.ArtId }, "INDEX_A");

                entity.HasIndex(e => new { e.Dos, e.Desabr, e.ArtId }, "INDEX_B");

                entity.HasIndex(e => new { e.Dos, e.Ean, e.ArtId }, "INDEX_I")
                    .HasFilter("([CE4]='1')");

                entity.HasIndex(e => new { e.Dos, e.Fam0001, e.Ref, e.ArtId }, "INDEX_J")
                    .HasFilter("([CE5]='1')");

                entity.HasIndex(e => new { e.Dos, e.Fam0002, e.Ref, e.ArtId }, "INDEX_K")
                    .HasFilter("([CE6]='1')");

                entity.HasIndex(e => new { e.Dos, e.Fam0003, e.Ref, e.ArtId }, "INDEX_L")
                    .HasFilter("([CE" +
                    "" +
                    "" +
                    "" +
                    "" +
                    "" +
                    "7]='1')");

                entity.HasIndex(e => new { e.Dos, e.Tiers, e.Ref, e.ArtId }, "INDEX_M")
                    .HasFilter("([CE8]='1')");

                entity.HasIndex(e => new { e.Dos, e.Prodnat, e.Ref, e.ArtId }, "INDEX_Z");

                entity.Property(e => e.ArtId).HasColumnName("ART_ID");

                entity.Property(e => e.Abccod)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("ABCCOD")
                    .IsFixedLength()
                    .HasComment("Code abc");

                entity.Property(e => e.Achrefamr)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ACHREFAMR")
                    .IsFixedLength()
                    .HasComment("Classe de remise article achat");

                entity.Property(e => e.Achrefamrx)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ACHREFAMRX")
                    .IsFixedLength()
                    .HasComment("Classe de remise article achat exceptionnelle");

                entity.Property(e => e.Achtafamr)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ACHTAFAMR")
                    .IsFixedLength()
                    .HasComment("Famille de tarification");

                entity.Property(e => e.Achtafamrx)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("ACHTAFAMRX")
                    .IsFixedLength()
                    .HasComment("Famille de tarification promotion article exceptionnelle");

                entity.Property(e => e.Achun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("ACHUN")
                    .IsFixedLength()
                    .HasComment("Unité d achat");

                entity.Property(e => e.Axemsk)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("AXEMSK")
                    .IsFixedLength()
                    .HasComment("Masque analytique");

                entity.Property(e => e.Axeno)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("AXENO")
                    .HasComment("No axe  analytique");

                entity.Property(e => e.Cbngescod)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("CBNGESCOD")
                    .IsFixedLength()
                    .HasComment("Code règle de gestion du CBN");

                entity.Property(e => e.Cdeclqte)
                    .HasColumnType("numeric(13, 3)")
                    .HasColumnName("CDECLQTE")
                    .HasComment("Quantité en commande client");

                entity.Property(e => e.Cdefoqte)
                    .HasColumnType("numeric(13, 3)")
                    .HasColumnName("CDEFOQTE")
                    .HasComment("Quantité en commande fournisseur");

                entity.Property(e => e.Cdeinqte)
                    .HasColumnType("numeric(13, 3)")
                    .HasColumnName("CDEINQTE")
                    .HasComment("Quantité en OF");

                entity.Property(e => e.Ce1)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE1")
                    .IsFixedLength()
                    .HasComment("Ce1");

                entity.Property(e => e.Ce2)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE2")
                    .IsFixedLength()
                    .HasComment("Ce2");

                entity.Property(e => e.Ce3)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE3")
                    .IsFixedLength()
                    .HasComment("Ce3");

                entity.Property(e => e.Ce4)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE4")
                    .IsFixedLength()
                    .HasComment("Ce4");

                entity.Property(e => e.Ce5)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE5")
                    .IsFixedLength()
                    .HasComment("Ce5");

                entity.Property(e => e.Ce6)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE6")
                    .IsFixedLength()
                    .HasComment("Ce6");

                entity.Property(e => e.Ce7)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE7")
                    .IsFixedLength()
                    .HasComment("Ce7");

                entity.Property(e => e.Ce8)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE8")
                    .IsFixedLength()
                    .HasComment("Ce8");

                entity.Property(e => e.Ce9)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE9")
                    .IsFixedLength()
                    .HasComment("Ce9");

                entity.Property(e => e.Cea)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CEA")
                    .IsFixedLength()
                    .HasComment("CeA");

                entity.Property(e => e.Cejoint)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("CEJOINT")
                    .HasComment("CE si fichier joint =2 si joint <> 0");

                entity.Property(e => e.Cenote)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("CENOTE")
                    .HasComment("=2 si note<> 0");

                entity.Property(e => e.Coefoivol)
                    .HasColumnType("numeric(6, 3)")
                    .HasColumnName("COEFOIVOL")
                    .HasComment("Coefficient de foisonnement sur le volume");

                entity.Property(e => e.Coefpts)
                    .HasColumnType("numeric(8, 3)")
                    .HasColumnName("COEFPTS")
                    .HasComment("Coefficient diviseur fidélité");

                entity.Property(e => e.Cofamr)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("COFAMR")
                    .IsFixedLength()
                    .HasComment("Famille de commission article");

                entity.Property(e => e.Competcod)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("COMPETCOD")
                    .IsFixedLength()
                    .HasComment("Code compétence");

                entity.Property(e => e.Comsais)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("COMSAIS")
                    .HasComment("Autoriser saisie de commission");

                entity.Property(e => e.Conf)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("CONF")
                    .IsFixedLength()
                    .HasComment("Code confidentiel");

                entity.Property(e => e.Configurateurchemincod)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("CONFIGURATEURCHEMINCOD")
                    .IsFixedLength()
                    .HasComment("Chemin du configurateur");

                entity.Property(e => e.Configurateurformulaire)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("CONFIGURATEURFORMULAIRE")
                    .IsFixedLength()
                    .HasComment("Formulaire du configurateur");

                entity.Property(e => e.Contratcod)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("CONTRATCOD")
                    .IsFixedLength()
                    .HasComment("");

                entity.Property(e => e.Contratfam)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("CONTRATFAM")
                    .IsFixedLength()
                    .HasComment("");

                entity.Property(e => e.Cpta)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("CPTA")
                    .IsFixedLength()
                    .HasComment("Compte d achat");

                entity.Property(e => e.Cptaces)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("CPTACES")
                    .IsFixedLength()
                    .HasComment("Compte d achat inter établissement");

                entity.Property(e => e.Cpts)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("CPTS")
                    .IsFixedLength()
                    .HasComment("Compte de stock");

                entity.Property(e => e.Cptv)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("CPTV")
                    .IsFixedLength()
                    .HasComment("Compte de vente");

                entity.Property(e => e.Cptvces)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("CPTVCES")
                    .IsFixedLength()
                    .HasComment("Compte de vente inter établissement");

                entity.Property(e => e.Deeecpta)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("DEEECPTA")
                    .IsFixedLength()
                    .HasComment("Compte de l éco-contribution en achat");

                entity.Property(e => e.Deeecptv)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("DEEECPTV")
                    .IsFixedLength()
                    .HasComment("Compte de l éco-contribution en vente");

                entity.Property(e => e.Deeepu)
                    .HasColumnType("numeric(9, 4)")
                    .HasColumnName("DEEEPU")
                    .HasComment("Prix unitaire éco-contribution");

                entity.Property(e => e.Deeeun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("DEEEUN")
                    .IsFixedLength()
                    .HasComment("Unité de l éco-contribution");

                entity.Property(e => e.Des)
                    .IsRequired()
                    .HasMaxLength(80)
                    .IsUnicode(false)
                    .HasColumnName("DES")
                    .IsFixedLength()
                    .HasComment("Désignation");

                entity.Property(e => e.Desabr)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("DESABR")
                    .IsFixedLength()
                    .HasComment("Désignation abrégée");

                entity.Property(e => e.Dim0001)
                    .HasColumnType("numeric(8, 3)")
                    .HasColumnName("DIM_0001")
                    .HasComment("Dimensions");

                entity.Property(e => e.Dim0002)
                    .HasColumnType("numeric(8, 3)")
                    .HasColumnName("DIM_0002")
                    .HasComment("Dimensions");

                entity.Property(e => e.Dim0003)
                    .HasColumnType("numeric(8, 3)")
                    .HasColumnName("DIM_0003")
                    .HasComment("Dimensions");

                entity.Property(e => e.Dimun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("DIMUN")
                    .IsFixedLength()
                    .HasComment("Unité des dimensions");

                entity.Property(e => e.Dopdh)
                    .HasColumnName("DOPDH")
                    .HasComment("Date et heure de dernière opération");

                entity.Property(e => e.Dos)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("DOS")
                    .HasComment("Dossier");

                entity.Property(e => e.Dtind)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("DTIND")
                    .IsFixedLength()
                    .HasComment("");

                entity.Property(e => e.Dvno)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("DVNO")
                    .HasComment("");

                entity.Property(e => e.Ean)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("EAN")
                    .IsFixedLength()
                    .HasComment("Code EAN");

                entity.Property(e => e.Eanautofl)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("EANAUTOFL")
                    .HasComment("");

                entity.Property(e => e.Edcod)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .HasColumnName("EDCOD")
                    .IsFixedLength()
                    .HasComment("Code édition");

                entity.Property(e => e.Fam0001)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("FAM_0001")
                    .IsFixedLength()
                    .HasComment("Famille statistique article");

                entity.Property(e => e.Fam0002)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("FAM_0002")
                    .IsFixedLength()
                    .HasComment("Famille statistique article");

                entity.Property(e => e.Fam0003)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("FAM_0003")
                    .IsFixedLength()
                    .HasComment("Famille statistique article");

                entity.Property(e => e.Garjrnb)
                    .HasColumnType("numeric(4, 0)")
                    .HasColumnName("GARJRNB")
                    .HasComment("Durée de garantie");

                entity.Property(e => e.Gicod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("GICOD")
                    .HasComment("Code global / individuel");

                entity.Property(e => e.Gricod)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("GRICOD")
                    .IsFixedLength()
                    .HasComment("Code grille sous-référence");

                entity.Property(e => e.Grisais)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("GRISAIS")
                    .HasComment("Saisie en mode grille");

                entity.Property(e => e.Hsdt)
                    .HasColumnType("date")
                    .HasColumnName("HSDT")
                    .HasComment("Date de fin de validité");

                entity.Property(e => e.Html)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("HTML")
                    .IsFixedLength()
                    .HasComment("Nom de la page html");

                entity.Property(e => e.Icpfl)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("ICPFL")
                    .HasComment("");

                entity.Property(e => e.Invdt)
                    .HasColumnType("date")
                    .HasColumnName("INVDT")
                    .HasComment("Date d inventaire");

                entity.Property(e => e.Joint)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("JOINT")
                    .HasComment("Numéro fichier joint");

                entity.Property(e => e.Lgtyp)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("LGTYP")
                    .HasComment("Type de ligne liée");

                entity.Property(e => e.Manun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("MANUN")
                    .IsFixedLength()
                    .HasComment("Unité de manutention");

                entity.Property(e => e.Media)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("MEDIA")
                    .IsFixedLength()
                    .HasComment("Image multimédia");

                entity.Property(e => e.Mgtx)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("MGTX")
                    .HasComment("Taux de marge");

                entity.Property(e => e.Note)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("NOTE")
                    .HasComment("Numéro de note");

                entity.Property(e => e.Opsais0001)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("OPSAIS_0001")
                    .HasComment("Option saisie vente");

                entity.Property(e => e.Opsais0002)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("OPSAIS_0002")
                    .HasComment("Option saisie vente");

                entity.Property(e => e.Opsais0003)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("OPSAIS_0003")
                    .HasComment("Option saisie vente");

                entity.Property(e => e.Pdp)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("PDP")
                    .HasComment("Indicateur PDP Master Product");

                entity.Property(e => e.Pdpdelobt)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("PDPDELOBT")
                    .HasComment("Délai d obtention PDP");

                entity.Property(e => e.Pdpecartmax)
                    .HasColumnType("numeric(4, 0)")
                    .HasColumnName("PDPECARTMAX")
                    .HasComment("Taux d écart maximum en % pour message PDP");

                entity.Property(e => e.Pdpfermepernb)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("PDPFERMEPERNB")
                    .HasComment("Nombre de périodes PDP ferme");

                entity.Property(e => e.Pdplotqte)
                    .HasColumnType("numeric(13, 3)")
                    .HasColumnName("PDPLOTQTE")
                    .HasComment("Taille de lot PDP");

                entity.Property(e => e.Pdpnegopernb)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("PDPNEGOPERNB")
                    .HasComment("Nombre de périodes PDP négociable");

                entity.Property(e => e.Pdppercod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("PDPPERCOD")
                    .HasComment("Période PDP");

                entity.Property(e => e.Pdpregpernb)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("PDPREGPERNB")
                    .HasComment("Nombre de périodes PDP regroupement");

                entity.Property(e => e.Perjrnb)
                    .HasColumnType("numeric(4, 0)")
                    .HasColumnName("PERJRNB")
                    .HasComment("Péremption en nombre de jours");

                entity.Property(e => e.Poib)
                    .HasColumnType("numeric(8, 3)")
                    .HasColumnName("POIB")
                    .HasComment("Poids brut");

                entity.Property(e => e.Poin)
                    .HasColumnType("numeric(8, 3)")
                    .HasColumnName("POIN")
                    .HasComment("Masse nette");

                entity.Property(e => e.Poiun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("POIUN")
                    .IsFixedLength()
                    .HasComment("Unité du poids");

                entity.Property(e => e.Prodnat)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("PRODNAT")
                    .IsFixedLength()
                    .HasComment("Nature du produit");

                entity.Property(e => e.Pvcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("PVCOD")
                    .HasComment("Code prix de vente");

                entity.Property(e => e.Question)
                    .IsRequired()
                    .HasMaxLength(32)
                    .IsUnicode(false)
                    .HasColumnName("QUESTION")
                    .IsFixedLength()
                    .HasComment("Questionnaire implicite dynamique");

                entity.Property(e => e.Rangabc)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("RANGABC")
                    .HasComment("Rang calcul ABC");

                entity.Property(e => e.Ref)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("REF")
                    .IsFixedLength()
                    .HasComment("Référence");

                entity.Property(e => e.Refamr)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("REFAMR")
                    .IsFixedLength()
                    .HasComment("Famille de remise");

                entity.Property(e => e.Refamrx)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("REFAMRX")
                    .IsFixedLength()
                    .HasComment("Famille remise exceptionnelle");

                entity.Property(e => e.Refrpl)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("REFRPL")
                    .IsFixedLength()
                    .HasComment("Référence de remplacement");

                entity.Property(e => e.Refun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("REFUN")
                    .IsFixedLength()
                    .HasComment("Unité de référence");

                entity.Property(e => e.Rejalcde)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("REJALCDE")
                    .HasComment("Autoriser le rejalonnement des commandes");

                entity.Property(e => e.Rejalcdejrnb)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("REJALCDEJRNB")
                    .HasComment("Horizon de rejalonnement des commandes");

                entity.Property(e => e.Rejalof)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("REJALOF")
                    .HasComment("Autoriser le rejalonnement des OFs");

                entity.Property(e => e.Rejalofjrnb)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("REJALOFJRNB")
                    .HasComment("Horizon de rejalonnement des OFs");

                entity.Property(e => e.Restotqte)
                    .HasColumnType("numeric(13, 3)")
                    .HasColumnName("RESTOTQTE")
                    .HasComment("Quantité en réservation client");

                entity.Property(e => e.Revuart)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("REVUART")
                    .HasComment("");

                entity.Property(e => e.Smcfl)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("SMCFL")
                    .HasComment("Flag ordonnancement SMC");

                entity.Property(e => e.Smcvisufl)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("SMCVISUFL")
                    .HasComment("Flag visualisation SMC");

                entity.Property(e => e.Sref1)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SREF1")
                    .IsFixedLength()
                    .HasComment("");

                entity.Property(e => e.Sref2)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SREF2")
                    .IsFixedLength()
                    .HasComment("");
                entity.Property(e => e.U_ACTIF)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("U_ACTIF")
                    .IsFixedLength()
                    .HasComment("");
                entity.Property(e => e.U_PTS)
    .IsRequired()
    .HasMaxLength(8)
    .IsUnicode(false)
    .HasColumnName("U_PTS")
    .IsFixedLength()
    .HasComment("");

                entity.Property(e => e.Srefcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("SREFCOD")
                    .HasComment("Gérer sous-référence non/oui");

                entity.Property(e => e.Stcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("STCOD")
                    .HasComment("Code stock / hors stock");

                entity.Property(e => e.Stlgtabccod)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("STLGTABCCOD")
                    .IsFixedLength()
                    .HasComment("Type de catégorie ABC");

                entity.Property(e => e.Stlgthgcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("STLGTHGCOD")
                    .HasComment("Hors gabarit oui/non");

                entity.Property(e => e.Stlgthgcolinb)
                    .HasColumnType("numeric(6, 3)")
                    .HasColumnName("STLGTHGCOLINB")
                    .HasComment("Nombre de colis nécessaire hors gabarit");

                entity.Property(e => e.Stres)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("STRES")
                    .HasComment("Réservation du stock ?");

                entity.Property(e => e.Stsorcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("STSORCOD")
                    .HasComment("Mode de sortie du stock");

                entity.Property(e => e.Sttotqte)
                    .HasColumnType("numeric(13, 3)")
                    .HasColumnName("STTOTQTE")
                    .HasComment("Quantité en stock cumulée");

                entity.Property(e => e.Stun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("STUN")
                    .IsFixedLength()
                    .HasComment("Unité de stockage");

                entity.Property(e => e.Stvalcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("STVALCOD")
                    .HasComment("Méthode de valorisation du stock");

                entity.Property(e => e.Surf)
                    .HasColumnType("numeric(8, 3)")
                    .HasColumnName("SURF")
                    .HasComment("Surface");

                entity.Property(e => e.Surfun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("SURFUN")
                    .IsFixedLength()
                    .HasComment("Unité de surface");

                entity.Property(e => e.Tafamr)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TAFAMR")
                    .IsFixedLength()
                    .HasComment("Famille de tarification");

                entity.Property(e => e.Tafamrx)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TAFAMRX")
                    .IsFixedLength()
                    .HasComment("Famille tarif exceptionnelle");

                entity.Property(e => e.Taref)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("TAREF")
                    .IsFixedLength()
                    .HasComment("Référence de tarification");

                entity.Property(e => e.Tiers)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TIERS")
                    .IsFixedLength()
                    .HasComment("Code tiers");

                entity.Property(e => e.Tierscli)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TIERSCLI")
                    .IsFixedLength()
                    .HasComment("");

                entity.Property(e => e.Tolerancetx)
                    .HasColumnType("numeric(5, 2)")
                    .HasColumnName("TOLERANCETX")
                    .HasComment("Taux de tolérance");

                entity.Property(e => e.Tpfr0001)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("TPFR_0001")
                    .HasComment("Code TPF article");

                entity.Property(e => e.Tpfr0002)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("TPFR_0002")
                    .HasComment("Code TPF article");

                entity.Property(e => e.Tpfr0003)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("TPFR_0003")
                    .HasComment("Code TPF article");

                entity.Property(e => e.Travun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("TRAVUN")
                    .IsFixedLength()
                    .HasComment("");

                entity.Property(e => e.Tvaart)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TVAART")
                    .IsFixedLength()
                    .HasComment("Régime TVA article");

                entity.Property(e => e.Tvaarta)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TVAARTA")
                    .IsFixedLength()
                    .HasComment("Régime TVA article achat");

                entity.Property(e => e.Tvanom)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false)
                    .HasColumnName("TVANOM")
                    .IsFixedLength()
                    .HasComment("Tva nomenclature douane");

                entity.Property(e => e.Tvargcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("TVARGCOD")
                    .HasComment("TVA code régime échange");

                entity.Property(e => e.Tvaun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("TVAUN")
                    .IsFixedLength()
                    .HasComment("Tva unité douanière");

                entity.Property(e => e.Usercr)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERCR")
                    .IsFixedLength()
                    .HasComment("Auteur de la création");

                entity.Property(e => e.Usercrdh)
                    .HasColumnName("USERCRDH")
                    .HasComment("Utilisateur date et heure de création");

                entity.Property(e => e.Usermo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERMO")
                    .IsFixedLength()
                    .HasComment("Auteur de la modification");

                entity.Property(e => e.Usermodh)
                    .HasColumnName("USERMODH")
                    .HasComment("Utilisateur date et heure de modification");

                entity.Property(e => e.Venun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("VENUN")
                    .IsFixedLength()
                    .HasComment("Unité de vente");

                entity.Property(e => e.Vol)
                    .HasColumnType("numeric(10, 3)")
                    .HasColumnName("VOL")
                    .HasComment("Volume");

                entity.Property(e => e.Volun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("VOLUN")
                    .IsFixedLength()
                    .HasComment("Unité du volume");

                entity.Property(e => e.Webcdecod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("WEBCDECOD")
                    .HasComment("Prise de commande par internet ?");

                entity.Property(e => e.Wmqteimp)
                    .HasColumnType("numeric(9, 0)")
                    .HasColumnName("WMQTEIMP")
                    .HasComment("Quantité seuil méthode de réservation en volume important");

                entity.Property(e => e.Wmreapfroidfl)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("WMREAPFROIDFL")
                    .HasComment("");

                entity.Property(e => e.Zona)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("ZONA")
                    .IsFixedLength()
                    .HasComment("Zone alpha libre");

                entity.Property(e => e.Zonn)
                    .HasColumnType("numeric(16, 3)")
                    .HasColumnName("ZONN")
                    .HasComment("Zone libre numérique");
            });
            modelBuilder.Entity<T006>(entity =>
            {
                entity.ToTable("T006");

                entity.HasKey(e => e.T006_ID);


            });
            modelBuilder.Entity<T012>(entity =>
            {
                entity.HasComment("Famille statistique article");

                entity.HasIndex(e => new { e.Dos, e.Cebin, e.Famno, e.Fam, e.T012Id }, "INDEX_A_T012");

                entity.Property(e => e.T012Id).HasColumnName("T012_ID");

                entity.Property(e => e.Cebin)
                    .HasColumnName("CEBIN")
                    .HasComment("CE binaire");

                entity.Property(e => e.Cenote)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("CENOTE")
                    .HasComment("=2 si note<> 0");

                entity.Property(e => e.Dos)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("DOS")
                    .HasComment("Dossier");

                entity.Property(e => e.Fam)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("FAM")
                    .IsFixedLength()
                    .HasComment("Famille statistique article");

                entity.Property(e => e.Famno)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("FAMNO")
                    .HasComment("Numéro famille article");

                entity.Property(e => e.Lib)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("LIB")
                    .IsFixedLength()
                    .HasComment("Libellé");

                entity.Property(e => e.Note)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("NOTE")
                    .HasComment("Numéro de note");

                entity.Property(e => e.Question)
                    .IsRequired()
                    .HasMaxLength(32)
                    .IsUnicode(false)
                    .HasColumnName("QUESTION")
                    .IsFixedLength()
                    .HasComment("Questionnaire implicite dynamique");

                entity.Property(e => e.Tabno)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("TABNO")
                    .HasComment("Numéro table de gtftab");

                entity.Property(e => e.Usercr)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERCR")
                    .IsFixedLength()
                    .HasComment("Auteur de la création");

                entity.Property(e => e.Usercrdh)
                    .HasColumnName("USERCRDH")
                    .HasComment("Utilisateur date et heure de création");

                entity.Property(e => e.Usermo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERMO")
                    .IsFixedLength()
                    .HasComment("Auteur de la modification");

                entity.Property(e => e.Usermodh)
                    .HasColumnName("USERMODH")
                    .HasComment("Utilisateur date et heure de modification");
            });
            modelBuilder.Entity<T019>(entity =>
            {
                entity.HasComment("Sous-référence");

                entity.HasIndex(e => new { e.Dos, e.Cebin, e.Sref1, e.T019Id }, "INDEX_A_T019");

                entity.Property(e => e.T019Id).HasColumnName("T019_ID");

                entity.Property(e => e.Cebin)
                    .HasColumnName("CEBIN")
                    .HasComment("CE binaire");

                entity.Property(e => e.Cenote)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("CENOTE")
                    .HasComment("=2 si note<> 0");

                entity.Property(e => e.Dos)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("DOS")
                    .IsFixedLength()
                    .HasComment("Dossier");

                entity.Property(e => e.Lib)
                    .IsRequired()
                    .HasMaxLength(40)
                    .IsUnicode(false)
                    .HasColumnName("LIB")
                    .IsFixedLength()
                    .HasComment("Libellé");

                entity.Property(e => e.Note)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("NOTE")
                    .HasComment("Numéro de note");

                entity.Property(e => e.Sref1)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SREF1")
                    .IsFixedLength()
                    .HasComment("Sous-référence 1");

                entity.Property(e => e.Srefrang)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("SREFRANG")
                    .IsFixedLength()
                    .HasComment("Rang de la sous-référence en mode grille");

                entity.Property(e => e.Tabno)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("TABNO")
                    .HasComment("Numéro table de gtftab");

                entity.Property(e => e.Usercr)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERCR")
                    .IsFixedLength()
                    .HasComment("Auteur de la création");

                entity.Property(e => e.Usercrdh)
                    .HasColumnName("USERCRDH")
                    .HasComment("Utilisateur date et heure de création");

                entity.Property(e => e.Usermo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERMO")
                    .IsFixedLength()
                    .HasComment("Auteur de la modification");

                entity.Property(e => e.Usermodh)
                    .HasColumnName("USERMODH")
                    .HasComment("Utilisateur date et heure de modification");
            });
            modelBuilder.Entity<Tar>(entity =>
            {
                entity.ToTable("TAR");

                entity.HasComment("Tarif de vente");

                entity.HasIndex(e => new { e.Dos, e.Ref, e.Sref1, e.Sref2, e.Tiers, e.Marche, e.Tacod, e.Venun, e.Dev, e.Depo, e.Tadt, e.Qte, e.TarId }, "INDEX_E");

                entity.HasIndex(e => new { e.Dos, e.Tacod, e.Tiers, e.Marche, e.Ref, e.Sref1, e.Sref2, e.Venun, e.Dev, e.Depo, e.Tadt, e.Qte, e.TarId }, "INDEX_F");

                entity.Property(e => e.TarId).HasColumnName("TAR_ID");

                entity.Property(e => e.Ce1)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE1")
                    .IsFixedLength()
                    .HasComment("Ce1");

                entity.Property(e => e.Ce2)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE2")
                    .IsFixedLength()
                    .HasComment("Ce2");

                entity.Property(e => e.Ce3)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE3")
                    .IsFixedLength()
                    .HasComment("Ce3");

                entity.Property(e => e.Ce4)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE4")
                    .IsFixedLength()
                    .HasComment("Ce4");

                entity.Property(e => e.Ce5)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE5")
                    .IsFixedLength()
                    .HasComment("Ce5");

                entity.Property(e => e.Ce6)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE6")
                    .IsFixedLength()
                    .HasComment("Ce6");

                entity.Property(e => e.Ce7)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE7")
                    .IsFixedLength()
                    .HasComment("Ce7");

                entity.Property(e => e.Ce8)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE8")
                    .IsFixedLength()
                    .HasComment("Ce8");

                entity.Property(e => e.Ce9)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CE9")
                    .IsFixedLength()
                    .HasComment("Ce9");

                entity.Property(e => e.Cea)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .HasColumnName("CEA")
                    .IsFixedLength()
                    .HasComment("CeA");

                entity.Property(e => e.Cenote)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("CENOTE")
                    .HasComment("=2 si note<> 0");

                entity.Property(e => e.Coe)
                    .HasColumnType("numeric(6, 3)")
                    .HasColumnName("COE")
                    .HasComment("Coefficient");

                entity.Property(e => e.Conf)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("CONF")
                    .IsFixedLength()
                    .HasComment("Code confidentiel");

                entity.Property(e => e.Depo)
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("DEPO")
                    .IsFixedLength()
                    .HasComment("Dépôt");

                entity.Property(e => e.Dev)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("DEV")
                    .IsFixedLength()
                    .HasComment("Devise");

                entity.Property(e => e.Dos)
                    .HasColumnType("numeric(3, 0)")
                    .HasColumnName("DOS")
                    .HasComment("Dossier");

                entity.Property(e => e.Hsdt)
                    .HasColumnType("date")
                    .HasColumnName("HSDT")
                    .HasComment("Date de fin de validité");

                entity.Property(e => e.Htcod)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("HTCOD")
                    .HasComment("Type tarif (HT ou TTC)");

                entity.Property(e => e.Icpfl)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("ICPFL")
                    .HasComment("");

                entity.Property(e => e.Marche)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("MARCHE")
                    .IsFixedLength()
                    .HasComment("Code marché");

                entity.Property(e => e.Marqte)
                    .HasColumnType("numeric(12, 3)")
                    .HasColumnName("MARQTE")
                    .HasComment("Quantité engagement pour le marché");

                entity.Property(e => e.Note)
                    .HasColumnType("numeric(8, 0)")
                    .HasColumnName("NOTE")
                    .HasComment("Numéro de note");

                entity.Property(e => e.Paforf)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("PAFORF")
                    .HasComment("Prix forfaitaire (1 = Non ; 2 = Oui)");

                entity.Property(e => e.Ppar)
                    .HasColumnType("numeric(12, 3)")
                    .HasColumnName("PPAR")
                    .HasComment("Prix par");

                entity.Property(e => e.Pub)
                    .HasColumnType("numeric(12, 3)")
                    .HasColumnName("PUB")
                    .HasComment("Prix unitaire brut");

                entity.Property(e => e.Pubtyp)
                    .HasColumnType("numeric(1, 0)")
                    .HasColumnName("PUBTYP")
                    .HasComment("Type de prix 1=brut, 2=net");

                entity.Property(e => e.Pubun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("PUBUN")
                    .IsFixedLength()
                    .HasComment("Unité du prix unitaire");

                entity.Property(e => e.Qte)
                    .HasColumnType("numeric(12, 3)")
                    .HasColumnName("QTE")
                    .HasComment("Quantité");

                entity.Property(e => e.Ref)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("REF")
                    .IsFixedLength()
                    .HasComment("Référence");

                entity.Property(e => e.Sref1)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SREF1")
                    .IsFixedLength()
                    .HasComment("Sous-référence 1");

                entity.Property(e => e.Sref2)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("SREF2")
                    .IsFixedLength()
                    .HasComment("Sous-référence 2");

                entity.Property(e => e.Tacod)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TACOD")
                    .IsFixedLength()
                    .HasComment("Code tarif HT");

                entity.Property(e => e.Tadt)
                    .HasColumnType("date")
                    .HasColumnName("TADT")
                    .HasComment("Date d application du tarif");

                entity.Property(e => e.Tiers)
                    .IsRequired()
                    .HasMaxLength(8)
                    .IsUnicode(false)
                    .HasColumnName("TIERS")
                    .IsFixedLength()
                    .HasComment("Code tiers");

                entity.Property(e => e.Usercr)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERCR")
                    .IsFixedLength()
                    .HasComment("Auteur de la création");

                entity.Property(e => e.Usercrdh)
                    .HasColumnName("USERCRDH")
                    .HasComment("Utilisateur date et heure de création");

                entity.Property(e => e.Usermo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("USERMO")
                    .IsFixedLength()
                    .HasComment("Auteur de la modification");

                entity.Property(e => e.Usermodh)
                    .HasColumnName("USERMODH")
                    .HasComment("Utilisateur date et heure de modification");

                entity.Property(e => e.Venun)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false)
                    .HasColumnName("VENUN")
                    .IsFixedLength()
                    .HasComment("Unité de vente");
            });
            modelBuilder.Entity<ChangePasswordRequest>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Username).IsRequired().HasMaxLength(100);
                entity.Property(e => e.OldPassword).IsRequired().HasMaxLength(255);
                entity.Property(e => e.NewPassword).IsRequired().HasMaxLength(255);
            });
            modelBuilder.Entity<Guest>(entity =>
            {
                entity.ToTable("Guest"); 

                entity.HasKey(e => e.Id);

                entity.Property(e => e.CliId)
                    .HasColumnType("int")
                    .IsRequired();
                entity.Property(e => e.Cin)
                    .HasColumnType("int")
                    .IsRequired();

                entity.Property(e => e.Num)
                    .HasColumnType("varchar(50)")
                    .IsRequired();

                entity.Property(e => e.Diva)
                    .HasColumnType("varchar(50)")
                    .IsRequired();
                entity.Property(e => e.Nom)
                    .HasColumnType("varchar(50)")
                    .IsRequired();

                entity.Property(e => e.Prenom)
                    .HasColumnType("varchar(50)")
                    .IsRequired();

                entity.Property(e => e.Tel)
                    .HasColumnType("varchar(50)")
                    .IsRequired();

                entity.Property(e => e.Adresse)
                    .HasColumnType("varchar(50)")
                    .IsRequired();

                entity.Property(e => e.Fidelite)
                    .HasColumnType("numeric(18, 0)")
                    .IsRequired();
            });


            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}