// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Olympia.Models
{
    /// <summary>
    /// Sous-référence
    /// </summary>
    public partial class T019
    {
        public int T019Id { get; set; }
        /// <summary>
        /// CE binaire
        /// </summary>
        public byte Cebin { get; set; }
        /// <summary>
        /// Dossier
        /// </summary>
        public decimal Dos { get; set; }
        /// <summary>
        /// Numéro table de gtftab
        /// </summary>
        public decimal Tabno { get; set; }
        /// <summary>
        /// Sous-référence 1
        /// </summary>
        public string Sref1 { get; set; }
        /// <summary>
        /// Auteur de la création
        /// </summary>
        public string Usercr { get; set; }
        /// <summary>
        /// Auteur de la modification
        /// </summary>
        public string Usermo { get; set; }
        /// <summary>
        /// Utilisateur date et heure de création
        /// </summary>
        public DateTime? Usercrdh { get; set; }
        /// <summary>
        /// Utilisateur date et heure de modification
        /// </summary>
        public DateTime? Usermodh { get; set; }
        /// <summary>
        /// =2 si note&lt;&gt; 0
        /// </summary>
        public decimal Cenote { get; set; }
        /// <summary>
        /// Numéro de note
        /// </summary>
        public decimal Note { get; set; }
        /// <summary>
        /// Libellé
        /// </summary>
        public string Lib { get; set; }
        /// <summary>
        /// Rang de la sous-référence en mode grille
        /// </summary>
        public string Srefrang { get; set; }
    }
}