// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Olympia.Models
{
    /// <summary>
    /// Code remise
    /// </summary>
    public partial class T035
    {
        public int T035Id { get; set; }
        /// <summary>
        /// CE binaire
        /// </summary>
        public byte Cebin { get; set; }
        /// <summary>
        /// Dossier
        /// </summary>
        public string Dos { get; set; }
        /// <summary>
        /// Numéro table de gtftab
        /// </summary>
        public decimal Tabno { get; set; }
        /// <summary>
        /// Type de tiers
        /// </summary>
        public string Ticod { get; set; }
        /// <summary>
        /// Code remise
        /// </summary>
        public string Remcod { get; set; }
        /// <summary>
        /// Auteur de la création
        /// </summary>
        public string Usercr { get; set; }
        /// <summary>
        /// Auteur de la modification
        /// </summary>
        public string Usermo { get; set; }
        /// <summary>
        /// Utilisateur date et heure de création
        /// </summary>
        public DateTime? Usercrdh { get; set; }
        /// <summary>
        /// Utilisateur date et heure de modification
        /// </summary>
        public DateTime? Usermodh { get; set; }
        /// <summary>
        /// =2 si note&lt;&gt; 0
        /// </summary>
        public decimal Cenote { get; set; }
        /// <summary>
        /// Numéro de note
        /// </summary>
        public decimal Note { get; set; }
        /// <summary>
        /// Libellé
        /// </summary>
        public string Lib { get; set; }
    }
}