// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Olympia.Models
{
    /// <summary>
    /// Tarif de vente
    /// </summary>
    public partial class Tar
    {
        public int TarId { get; set; }
        /// <summary>
        /// Ce1
        /// </summary>
        public string Ce1 { get; set; }
        /// <summary>
        /// Ce2
        /// </summary>
        public string Ce2 { get; set; }
        /// <summary>
        /// Ce3
        /// </summary>
        public string Ce3 { get; set; }
        /// <summary>
        /// Ce4
        /// </summary>
        public string Ce4 { get; set; }
        /// <summary>
        /// Ce5
        /// </summary>
        public string Ce5 { get; set; }
        /// <summary>
        /// Ce6
        /// </summary>
        public string Ce6 { get; set; }
        /// <summary>
        /// Ce7
        /// </summary>
        public string Ce7 { get; set; }
        /// <summary>
        /// Ce8
        /// </summary>
        public string Ce8 { get; set; }
        /// <summary>
        /// Ce9
        /// </summary>
        public string Ce9 { get; set; }
        /// <summary>
        /// CeA
        /// </summary>
        public string Cea { get; set; }
        /// <summary>
        /// Dossier
        /// </summary>
        public decimal Dos { get; set; }
        /// <summary>
        /// Référence
        /// </summary>
        public string Ref { get; set; }
        /// <summary>
        /// Sous-référence 1
        /// </summary>
        public string Sref1 { get; set; }
        /// <summary>
        /// Sous-référence 2
        /// </summary>
        public string Sref2 { get; set; }
        /// <summary>
        /// Code tiers
        /// </summary>
        public string Tiers { get; set; }
        /// <summary>
        /// Code marché
        /// </summary>
        public string Marche { get; set; }
        /// <summary>
        /// Code tarif HT
        /// </summary>
        public string Tacod { get; set; }
        /// <summary>
        /// Unité de vente
        /// </summary>
        public string Venun { get; set; }
        /// <summary>
        /// Devise
        /// </summary>
        public string Dev { get; set; }
        /// <summary>
        /// Dépôt
        /// </summary>
        public string Depo { get; set; }
        /// <summary>
        /// Date d application du tarif
        /// </summary>
        public DateTime? Tadt { get; set; }
        /// <summary>
        /// Quantité
        /// </summary>
        public decimal Qte { get; set; }
        /// <summary>
        /// Code confidentiel
        /// </summary>
        public string Conf { get; set; }
        /// <summary>
        /// Auteur de la création
        /// </summary>
        public string Usercr { get; set; }
        /// <summary>
        /// Auteur de la modification
        /// </summary>
        public string Usermo { get; set; }
        /// <summary>
        /// Utilisateur date et heure de création
        /// </summary>
        public DateTime? Usercrdh { get; set; }
        /// <summary>
        /// Utilisateur date et heure de modification
        /// </summary>
        public DateTime? Usermodh { get; set; }
        /// <summary>
        /// =2 si note&lt;&gt; 0
        /// </summary>
        public decimal Cenote { get; set; }
        /// <summary>
        /// Numéro de note
        /// </summary>
        public decimal Note { get; set; }
        /// <summary>
        /// Prix unitaire brut
        /// </summary>
        public decimal Pub { get; set; }
        /// <summary>
        /// Prix par
        /// </summary>
        public decimal Ppar { get; set; }
        /// <summary>
        /// Coefficient
        /// </summary>
        public decimal Coe { get; set; }
        /// <summary>
        /// Unité du prix unitaire
        /// </summary>
        public string Pubun { get; set; }
        /// <summary>
        /// Type tarif (HT ou TTC)
        /// </summary>
        public decimal Htcod { get; set; }
        /// <summary>
        /// Type de prix 1=brut, 2=net
        /// </summary>
        public decimal Pubtyp { get; set; }
        /// <summary>
        /// Quantité engagement pour le marché
        /// </summary>
        public decimal Marqte { get; set; }
        /// <summary>
        /// Prix forfaitaire (1 = Non ; 2 = Oui)
        /// </summary>
        public decimal Paforf { get; set; }
        /// <summary>
        /// Date de fin de validité
        /// </summary>
        public DateTime? Hsdt { get; set; }
        public decimal Icpfl { get; set; }
    }
}