// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Olympia.Models
{
    public partial class TarRemise
    {
        public decimal Dos { get; set; }
        public string Ref { get; set; }
        public string Sref1 { get; set; }
        public string Sref2 { get; set; }
        public string Remcod { get; set; }
        public decimal Rem0001 { get; set; }
        public decimal Rem0002 { get; set; }
        public string Lib { get; set; }
    }
}